name: Deploy Strapi Application

on:
  push:
    branches:
      - saipavan
  pull_request:
    branches:
      - saipavan

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.11

      - name: Initialize Terraform
        run: terraform init

      - name: Apply Terraform configuration
        run: terraform apply -auto-approve

  deploy:
    needs: terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy Strapi
        env:
          EC2_USER: ubuntu
          EC2_HOST: ${{ secrets.SAIPAVAN_EC2_HOST }}
          EC2_KEY: ${{ secrets.SAIPAVAN_EC2_KEY }}
        run: |
          ssh -o StrictHostKeyChecking=no -i $EC2_KEY $EC2_USER@$EC2_HOST "
            cd /srv/strapi
            git pull origin main
            sudo npm install
            sudo pm2 restart strapi
          "

