name: Deploy

on:
  push:
    branches:
      - main
      - PradyumnaNaik1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Sync Repository
        run: |
          ssh -i /path/to/your-key-pair.pem ec2-user@your-ec2-public-dns "cd /srv/strapi && git pull origin main && npm install && pm2 restart all"

