name: CI/CD

on:
  push:
    branches: [ master, your_branch_name ] # Trigger on push to master and your branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install npm dependencies
        run: npm install
      - name: Build Strapi app
        run: npm run build
      - name: Start Strapi server (replace with PM2 command)
        run: pm2 start npm -- start

