name: CI/CD

on:
  push:
    branches: [ main, Adam ] # Trigger on push to main and Adam branches

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install npm dependencies
        run: npm install

      - name: Build Strapi app
        run: npm run build

      - name: Install PM2
        run: npm install pm2 -g

      - name: Start Strapi server with PM2
        run: pm2 start npm --name "strapi" -- start
