name: Terraform Apply

on:
  push:
    branches:
      - Shaikgayas

jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.8.5'

      - name: Configure AWS credentials
        run: aws configure set aws_access_key_id ${{ secrets.SHAIKGAYASAWS_ACCESS_KEY_ID }} && aws configure set aws_secret_access_key ${{ secrets.SHAIKGAYASAWS_SECRET_ACCESS_KEY }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: |
          terraform validate
          terraform apply -auto-approve

      - name: Save Terraform state
        if: success()
        run: |
          STATE_DIR="${{ secrets.TF_STATE_DIR }}/terraform.tfstate"
          mkdir -p "$(dirname "$STATE_DIR")"
          mv terraform.tfstate "$STATE_DIR"
        shell: bash
        env:
          TERRAFORM_CLI_PATH: /home/runner/work/_temp/9e78564e-7073-4079-b117-c030bbab8522
