name: Terraform Apply

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy staging'
        required: true
        default: 'staging'

jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.0.0'

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: |
          terraform validate
          terraform apply -auto-approve
          terraform output public_ip_address > public_ip.txt  # Output public IP to a file

      - name: Show Public IP
        run: |
          cat public_ip.txt  # Display the public IP in the workflow log


      - name: Save Terraform state
        if: success()
        run: |
          mkdir -p ${{ secrets.TF_STATE_DIR }}
          mv terraform.tfstate ${{ secrets.TF_STATE_DIR }}/terraform.tfstate
